sudo: required
services:
 - docker

before_install:
 - docker build -t osamaliaqat/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true osamaliaqat/react-test npm test

after_success:
 - docker build -t osamaliaqat/multi-client ./client
 - docker build -t osamaliaqat/multi-nginx ./nginx
 - docker build -t osamaliaqat/multi-server ./server
 - docker build -t osamaliaqat/multi-worker ./worker
 # Log in to the docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take those images and push it to docker hub
 - docker push osamaliaqat/multi-client
 - docker push osamaliaqat/multi-nginx
 - docker push osamaliaqat/multi-server
 - docker push osamaliaqat/multi-worker
